import { Scale } from './types';

export const SCALES: Scale[] = [
  {
    id: 'phq9',
    name: 'PHQ-9',
    fullName: 'Patient Health Questionnaire-9',
    description: 'Escala de cribado y severidad de depresión. Evalúa los 9 síntomas del episodio depresivo mayor según el DSM-5.',
    estimatedMinutes: 3,
    reference: 'Kroenke et al., 2001',
    items: [
      { id: 1, text: 'Poco interés o placer en hacer las cosas', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 2, text: 'Sentirse decaído/a, deprimido/a o sin esperanzas', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 3, text: 'Problemas para quedarse o mantenerse dormido/a, o dormir demasiado', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 4, text: 'Sentirse cansado/a o tener poca energía', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 5, text: 'Poco apetito o comer en exceso', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 6, text: 'Sentirse mal consigo mismo/a, o sentir que es un fracaso o que ha fallado a sí mismo/a o a su familia', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 7, text: 'Tener dificultad para concentrarse en cosas tales como leer el periódico o ver televisión', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 8, text: 'Moverse o hablar tan lentamente que otras personas lo han notado, o lo contrario: estar tan inquieto/a o agitado/a que se mueve mucho más de lo normal', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 9, text: 'Pensamientos de que estaría mejor muerto/a o de que se haría daño de alguna manera', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
    ],
    scoringRanges: [
      { min: 0, max: 4, label: 'Sin depresión', color: '#10B981', recommendation: 'No se requiere tratamiento específico. Monitorear.' },
      { min: 5, max: 9, label: 'Depresión leve', color: '#F59E0B', recommendation: 'Psicoeducación y seguimiento. Considerar intervención si persiste.' },
      { min: 10, max: 14, label: 'Depresión moderada', color: '#F97316', recommendation: 'Iniciar plan de tratamiento TCC. Evaluar necesidad de medicación.' },
      { min: 15, max: 19, label: 'Depresión moderada-severa', color: '#EF4444', recommendation: 'Tratamiento activo recomendado. Considerar interconsulta psiquiátrica.' },
      { min: 20, max: 27, label: 'Depresión severa', color: '#7C3AED', recommendation: 'Tratamiento intensivo urgente. Interconsulta psiquiátrica inmediata.' },
    ],
  },
  {
    id: 'gad7',
    name: 'GAD-7',
    fullName: 'Generalized Anxiety Disorder-7',
    description: 'Escala de cribado y severidad del trastorno de ansiedad generalizada. Evalúa los síntomas de ansiedad en las últimas 2 semanas.',
    estimatedMinutes: 3,
    reference: 'Spitzer et al., 2006',
    items: [
      { id: 1, text: 'Sentirse nervioso/a, ansioso/a o al límite', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 2, text: 'No poder dejar de preocuparse o no poder controlar la preocupación', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 3, text: 'Preocuparse demasiado por diferentes cosas', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 4, text: 'Dificultad para relajarse', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 5, text: 'Estar tan inquieto/a que es difícil quedarse quieto/a', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 6, text: 'Molestarse o irritarse fácilmente', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
      { id: 7, text: 'Sentir miedo como si algo terrible fuera a pasar', options: [{ value: 0, label: 'Para nada' }, { value: 1, label: 'Varios días' }, { value: 2, label: 'Más de la mitad de los días' }, { value: 3, label: 'Casi todos los días' }] },
    ],
    scoringRanges: [
      { min: 0, max: 4, label: 'Ansiedad mínima', color: '#10B981', recommendation: 'No se requiere tratamiento específico. Monitorear.' },
      { min: 5, max: 9, label: 'Ansiedad leve', color: '#F59E0B', recommendation: 'Psicoeducación sobre ansiedad. Técnicas de relajación.' },
      { min: 10, max: 14, label: 'Ansiedad moderada', color: '#F97316', recommendation: 'Iniciar TCC para ansiedad. Técnicas de exposición y reestructuración.' },
      { min: 15, max: 21, label: 'Ansiedad severa', color: '#EF4444', recommendation: 'Tratamiento intensivo. Considerar interconsulta psiquiátrica.' },
    ],
  },
  {
    id: 'bdi2',
    name: 'BDI-II',
    fullName: 'Beck Depression Inventory-II',
    description: 'Inventario de depresión de Beck. Evalúa la presencia y gravedad de síntomas depresivos en adultos y adolescentes.',
    estimatedMinutes: 10,
    reference: 'Beck et al., 1996',
    items: [
      { id: 1, text: 'Tristeza', options: [{ value: 0, label: 'No me siento triste' }, { value: 1, label: 'Me siento triste gran parte del tiempo' }, { value: 2, label: 'Me siento triste todo el tiempo' }, { value: 3, label: 'Me siento tan triste o tan desgraciado/a que no puedo soportarlo' }] },
      { id: 2, text: 'Pesimismo', options: [{ value: 0, label: 'No estoy desalentado/a sobre mi futuro' }, { value: 1, label: 'Me siento más desalentado/a sobre mi futuro que antes' }, { value: 2, label: 'No espero que las cosas mejoren' }, { value: 3, label: 'Siento que mi futuro es desesperanzador y que las cosas solo empeorarán' }] },
      { id: 3, text: 'Fracasos del pasado', options: [{ value: 0, label: 'No me siento fracasado/a' }, { value: 1, label: 'He fracasado más de lo que debería' }, { value: 2, label: 'Cuando miro atrás, veo muchos fracasos' }, { value: 3, label: 'Siento que como persona soy un fracaso total' }] },
      { id: 4, text: 'Pérdida de placer', options: [{ value: 0, label: 'Obtengo tanto placer como siempre de las cosas que disfruto' }, { value: 1, label: 'No disfruto las cosas tanto como antes' }, { value: 2, label: 'Obtengo muy poco placer de las cosas que solía disfrutar' }, { value: 3, label: 'No puedo obtener ningún placer de las cosas que solía disfrutar' }] },
      { id: 5, text: 'Sentimientos de culpa', options: [{ value: 0, label: 'No me siento particularmente culpable' }, { value: 1, label: 'Me siento culpable por muchas cosas que he hecho o que debería haber hecho' }, { value: 2, label: 'Me siento bastante culpable la mayor parte del tiempo' }, { value: 3, label: 'Me siento culpable todo el tiempo' }] },
      { id: 6, text: 'Sentimientos de castigo', options: [{ value: 0, label: 'No siento que estoy siendo castigado/a' }, { value: 1, label: 'Siento que puedo ser castigado/a' }, { value: 2, label: 'Espero ser castigado/a' }, { value: 3, label: 'Siento que estoy siendo castigado/a' }] },
      { id: 7, text: 'Disconformidad con uno mismo', options: [{ value: 0, label: 'Siento lo mismo que antes sobre mí mismo/a' }, { value: 1, label: 'He perdido la confianza en mí mismo/a' }, { value: 2, label: 'Estoy decepcionado/a conmigo mismo/a' }, { value: 3, label: 'No me gusto' }] },
      { id: 8, text: 'Autocrítica', options: [{ value: 0, label: 'No me critico ni me culpo más que antes' }, { value: 1, label: 'Me critico más que antes' }, { value: 2, label: 'Me critico por todos mis errores' }, { value: 3, label: 'Me culpo por todo lo malo que sucede' }] },
      { id: 9, text: 'Pensamientos o deseos suicidas', options: [{ value: 0, label: 'No tengo ningún pensamiento de matarme' }, { value: 1, label: 'He tenido pensamientos de matarme, pero no lo haría' }, { value: 2, label: 'Querría matarme' }, { value: 3, label: 'Me mataría si tuviera la oportunidad de hacerlo' }] },
      { id: 10, text: 'Llanto', options: [{ value: 0, label: 'No lloro más de lo que solía hacerlo' }, { value: 1, label: 'Lloro más de lo que solía hacerlo' }, { value: 2, label: 'Lloro por cualquier pequeñez' }, { value: 3, label: 'Tengo ganas de llorar pero no puedo' }] },
      { id: 11, text: 'Agitación', options: [{ value: 0, label: 'No estoy más inquieto/a o agitado/a que de costumbre' }, { value: 1, label: 'Me siento más inquieto/a o agitado/a que de costumbre' }, { value: 2, label: 'Estoy tan inquieto/a o agitado/a que me es difícil quedarme quieto/a' }, { value: 3, label: 'Estoy tan inquieto/a o agitado/a que tengo que estar siempre en movimiento o haciendo algo' }] },
      { id: 12, text: 'Pérdida de interés', options: [{ value: 0, label: 'No he perdido el interés en otras personas o actividades' }, { value: 1, label: 'Estoy menos interesado/a que antes en otras personas o actividades' }, { value: 2, label: 'He perdido la mayor parte de mi interés en otras personas o actividades' }, { value: 3, label: 'Me es difícil interesarme en algo' }] },
      { id: 13, text: 'Indecisión', options: [{ value: 0, label: 'Tomo mis propias decisiones tan bien como siempre' }, { value: 1, label: 'Me es más difícil que de costumbre tomar decisiones' }, { value: 2, label: 'Encuentro mucha más dificultad que antes para tomar decisiones' }, { value: 3, label: 'Tengo problemas para tomar cualquier decisión' }] },
      { id: 14, text: 'Inutilidad', options: [{ value: 0, label: 'No me siento inútil' }, { value: 1, label: 'No me considero tan valioso/a y útil como solía considerarme' }, { value: 2, label: 'Me siento menos valioso/a en comparación con otras personas' }, { value: 3, label: 'Me siento completamente inútil' }] },
      { id: 15, text: 'Pérdida de energía', options: [{ value: 0, label: 'Tengo tanta energía como siempre' }, { value: 1, label: 'Tengo menos energía que la que solía tener' }, { value: 2, label: 'No tengo suficiente energía para hacer muchas cosas' }, { value: 3, label: 'No tengo suficiente energía para hacer nada' }] },
      { id: 16, text: 'Cambios en los hábitos de sueño', options: [{ value: 0, label: 'No he experimentado ningún cambio en mis hábitos de sueño' }, { value: 1, label: 'Duermo algo más/menos que de costumbre' }, { value: 2, label: 'Duermo mucho más/menos que de costumbre' }, { value: 3, label: 'Duermo la mayor parte del día / Me despierto 1-2 horas más temprano y no puedo volver a dormirme' }] },
      { id: 17, text: 'Irritabilidad', options: [{ value: 0, label: 'No estoy más irritable que de costumbre' }, { value: 1, label: 'Estoy más irritable que de costumbre' }, { value: 2, label: 'Estoy mucho más irritable que de costumbre' }, { value: 3, label: 'Estoy irritable todo el tiempo' }] },
      { id: 18, text: 'Cambios en el apetito', options: [{ value: 0, label: 'No he experimentado ningún cambio en mi apetito' }, { value: 1, label: 'Mi apetito es algo mayor/menor que de costumbre' }, { value: 2, label: 'Mi apetito es mucho mayor/menor que antes' }, { value: 3, label: 'No tengo ningún apetito / Tengo ganas de comer todo el tiempo' }] },
      { id: 19, text: 'Dificultad de concentración', options: [{ value: 0, label: 'Puedo concentrarme tan bien como siempre' }, { value: 1, label: 'No puedo concentrarme tan bien como habitualmente' }, { value: 2, label: 'Me es difícil mantener la mente en algo por mucho tiempo' }, { value: 3, label: 'Encuentro que no puedo concentrarme en nada' }] },
      { id: 20, text: 'Cansancio o fatiga', options: [{ value: 0, label: 'No estoy más cansado/a o fatigado/a que de costumbre' }, { value: 1, label: 'Me fatigo o me canso más fácilmente que de costumbre' }, { value: 2, label: 'Estoy demasiado fatigado/a o cansado/a para hacer muchas de las cosas que solía hacer' }, { value: 3, label: 'Estoy demasiado fatigado/a o cansado/a para hacer la mayoría de las cosas que solía hacer' }] },
      { id: 21, text: 'Pérdida de interés en el sexo', options: [{ value: 0, label: 'No he notado ningún cambio reciente en mi interés por el sexo' }, { value: 1, label: 'Estoy menos interesado/a en el sexo de lo que solía estarlo' }, { value: 2, label: 'Estoy mucho menos interesado/a en el sexo ahora' }, { value: 3, label: 'He perdido completamente el interés en el sexo' }] },
    ],
    scoringRanges: [
      { min: 0, max: 13, label: 'Depresión mínima', color: '#10B981', recommendation: 'Sin indicación de tratamiento. Seguimiento preventivo.' },
      { min: 14, max: 19, label: 'Depresión leve', color: '#F59E0B', recommendation: 'Psicoeducación y activación conductual. Monitorear.' },
      { min: 20, max: 28, label: 'Depresión moderada', color: '#F97316', recommendation: 'Tratamiento TCC estructurado. Evaluar medicación.' },
      { min: 29, max: 63, label: 'Depresión severa', color: '#EF4444', recommendation: 'Tratamiento intensivo urgente. Interconsulta psiquiátrica.' },
    ],
  },
  {
    id: 'bai',
    name: 'BAI',
    fullName: 'Beck Anxiety Inventory',
    description: 'Inventario de ansiedad de Beck. Mide la severidad de los síntomas de ansiedad, diferenciando entre ansiedad y depresión.',
    estimatedMinutes: 5,
    reference: 'Beck et al., 1988',
    items: [
      { id: 1, text: 'Entumecimiento u hormigueo', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 2, text: 'Sensación de calor', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 3, text: 'Debilidad en las piernas', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 4, text: 'Incapacidad de relajarse', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 5, text: 'Miedo a que ocurra lo peor', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 6, text: 'Mareos o vértigo', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 7, text: 'Palpitaciones o aceleración del corazón', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 8, text: 'Inestabilidad', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 9, text: 'Terror', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 10, text: 'Nerviosismo', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 11, text: 'Sensación de ahogo', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 12, text: 'Temblores', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 13, text: 'Temblor o estremecimiento', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 14, text: 'Miedo a perder el control', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 15, text: 'Dificultad para respirar', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 16, text: 'Miedo a morir', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 17, text: 'Asustado', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 18, text: 'Indigestión o malestar abdominal', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 19, text: 'Desmayos', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 20, text: 'Rubor facial', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
      { id: 21, text: 'Sudoración (no debida al calor)', options: [{ value: 0, label: 'En absoluto' }, { value: 1, label: 'Levemente' }, { value: 2, label: 'Moderadamente' }, { value: 3, label: 'Severamente' }] },
    ],
    scoringRanges: [
      { min: 0, max: 7, label: 'Ansiedad mínima', color: '#10B981', recommendation: 'Sin indicación de tratamiento específico.' },
      { min: 8, max: 15, label: 'Ansiedad leve', color: '#F59E0B', recommendation: 'Técnicas de relajación y psicoeducación.' },
      { min: 16, max: 25, label: 'Ansiedad moderada', color: '#F97316', recommendation: 'TCC para ansiedad. Técnicas de exposición.' },
      { min: 26, max: 63, label: 'Ansiedad severa', color: '#EF4444', recommendation: 'Tratamiento intensivo. Considerar medicación.' },
    ],
  },
  {
    id: 'dass21',
    name: 'DASS-21',
    fullName: 'Depression Anxiety Stress Scales-21',
    description: 'Escala de depresión, ansiedad y estrés. Evalúa tres dimensiones del malestar emocional en las últimas semanas.',
    estimatedMinutes: 5,
    reference: 'Lovibond & Lovibond, 1995',
    items: [
      { id: 1, text: 'Me costó mucho relajarme', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 2, text: 'Me di cuenta que tenía la boca seca', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 3, text: 'No podía sentir ningún sentimiento positivo', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 4, text: 'Se me hizo difícil respirar', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 5, text: 'Se me hizo difícil tomar la iniciativa para hacer cosas', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 6, text: 'Reaccioné exageradamente en ciertas situaciones', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 7, text: 'Sentí que mis manos temblaban', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 8, text: 'Sentí que tenía muchos nervios', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 9, text: 'Estaba preocupado por situaciones en las cuales podía tener pánico', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 10, text: 'Sentí que no tenía nada por qué vivir', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 11, text: 'Noté que me agitaba', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 12, text: 'Se me hizo difícil relajarme', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 13, text: 'Me sentí triste y deprimido/a', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 14, text: 'No toleré nada que me impidiera continuar con lo que estaba haciendo', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 15, text: 'Sentí que estaba al punto de pánico', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 16, text: 'No me pude entusiasmar por nada', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 17, text: 'Sentí que valía muy poco como persona', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 18, text: 'Sentí que estaba muy irritable', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 19, text: 'Sentí los latidos de mi corazón sin haber hecho ejercicio físico', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 20, text: 'Tuve miedo sin razón', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
      { id: 21, text: 'Sentí que la vida no tenía ningún sentido', options: [{ value: 0, label: 'No me ocurrió' }, { value: 1, label: 'Me ocurrió un poco, o durante parte del tiempo' }, { value: 2, label: 'Me ocurrió bastante, o durante una buena parte del tiempo' }, { value: 3, label: 'Me ocurrió mucho, o la mayor parte del tiempo' }] },
    ],
    scoringRanges: [
      { min: 0, max: 9, label: 'Normal', color: '#10B981', recommendation: 'Sin indicación de tratamiento.' },
      { min: 10, max: 12, label: 'Leve', color: '#F59E0B', recommendation: 'Monitorear y psicoeducación.' },
      { min: 13, max: 20, label: 'Moderado', color: '#F97316', recommendation: 'Intervención TCC recomendada.' },
      { min: 21, max: 27, label: 'Severo', color: '#EF4444', recommendation: 'Tratamiento intensivo.' },
      { min: 28, max: 63, label: 'Extremadamente severo', color: '#7C3AED', recommendation: 'Urgente: interconsulta psiquiátrica.' },
    ],
  },
];

export const getScaleById = (id: string): Scale | undefined =>
  SCALES.find((s) => s.id === id);

export const interpretScore = (scale: Scale, score: number): { label: string; color: string; recommendation: string } => {
  const range = scale.scoringRanges.find((r) => score >= r.min && score <= r.max);
  return range ?? { label: 'Sin datos', color: '#64748B', recommendation: '' };
};
